### ISSUE TITLE
`-A:test` option or similar?

### ISSUE THREAD

**Issue by eraserhd** [hlolli/clj2nix#1]
I'm using this to build `rep` with GraalVM's native-image.  It's working for that part, but I want to . run tests after, and this has a `:test` alias that needs to be merged in.  Is this a good idea?

EDIT: To be clear, this is in a `release.nix`, so it is a separate package that needs more dependencies, even though it uses the same `src` attribute.

**Comment by hlolli** [comment]
ahh I see, there are extra dependencies clj2nix doesn't pick up because they are under alias?

Yes, I should have accounted for that. I can add that.

Also thanks for using clj2nix, you're the first one I head about using this tool.

**Comment by hlolli** [comment]
I've added that possibility. Add -A:test at the end of your command and the extra-deps should be added to the nix derivation. Can you let me know if this is what you ment?
