### ISSUE TITLE
Warnings on clojure >= 1.10.1.697

### ISSUE THREAD

**Issue by jskrzypek** [hlolli/clj2nix#15]
I'm seeing this when running clj2nix on clojure 1.10.1.727, which was introduced by this commit: https://github.com/NixOS/nixpkgs/commit/43776fb11e17781ebffb3bd110b83af224aa5624
```
WARNING: When invoking clojure.main, use -M
```

I'll make a PR to condition the invocation based on the clojure version

**Comment by hlolli** [comment]
it's gone since yesterday, it was an annoying one.
