### ISSUE TITLE
Not respecting :mvn/repos?

### ISSUE THREAD

**Issue by WhittlesJr** [hlolli/clj2nix#3]
Is it possible that this application doesn't include :mvn/repos in its operations? I have a few dependencies that are not hosted on maven central, so I add this line to my deps.edn:

```clojure
:mvn/repos {"ias-releases" {:url "https://maven.mangoautomation.net/repository/ias-release/"}}
```

This works doing REPL or other normal operations, but clj2nix says that it can't find these dependencies.

**Comment by hlolli** [comment]
That’s true. Should be easy to add. I’m still on vacation but parsing the deps.edn and add the extra repos to fetchmaven here https://github.com/hlolli/clj2nix/blob/master/deps.nix#L4 would be the way to add this feature.

**Comment by WhittlesJr** [comment]
I can start working on this today, unless you've already begun
