### ISSUE TITLE
Describe implicit dependencies (shasum512, nix-prefetch-git)

### ISSUE THREAD

**Issue by thenonameguy** [hlolli/clj2nix#5]
On MacOS this is generally not available, so adding a note describing the installation of these would help.
`nix-shell -p coreutils nix-prefetch-git` helps until this is fixed.

**Comment by hlolli** [comment]
:facepalm: not good, this is a big NIX mistake there. I will fix, in such a way that I'd be calling https://github.com/hlolli/clj2nix/blob/master/clj2nix.clj#L82 this binary directly from nixpkgs namespace. I'd say this code was written long time ago, still not an excuse :fearful:

**Comment by hlolli** [comment]
@thenonameguy I think the PATH reference I added to the runtime wrapper should fix this, let me know if you still can't run clj2nix without defining these runtime dependencies.
