### ISSUE TITLE
Populate repos from :mvn/repos

### ISSUE THREAD

**Issue by terlar** [hlolli/clj2nix#9]
At work we are using mirrors for both central and clojars, it would be nice if the property `:mvn/repos` was taken into account and overriding all the repos defined. Alternatively (second best) if you could provide a repo or a list of repos via the CLI clj2nix to affect this variable.

Hopefuly this config inside `deps.edn`:
```
{:mvn/repos {"central" {:url "https://artifactory.domain/artifactory/v-maven-releases"}
             "clojars" {:url "https://artifactory.domain/artifactory/v-maven-releases"}}
...
```

Would result in this:
```
let repos = [ "https://artifactory.domain/artifactory/v-maven-releases" ];
```

**Comment by hlolli** [comment]
Sure, should be easy to change. I'll keep you updated.

**Comment by hlolli** [comment]
https://github.com/hlolli/clj2nix/commit/89d1cda232175b588c7774e638c9ebfaaedea0e3

This should fix this, now the mvn/repos mirrors take precedence over fallback. In such a way that the fallback is totally ignored. Also the fallback repos were also changed, as I copied it from fetchFromMaven derivation and it was very outdated.

**Comment by terlar** [comment]
Confirmed that this works, thank you very much!

**Comment by terlar** [comment]
Only thing to note, is that the list could be made to contain unique items. But it is not really bad if it is repeated as well, like now.
